owner: mikesprague
repo: skydark-status
user-agent: mikesprague
sites:
  - name: SkyDark
    url: https://skydark.app
#   - name: SkyDark API
#     url: $SKYDARK_API_URL
assignees:
  - mikesprague
status-website:
  cname: status.skydark.app
  logoUrl: https://raw.githubusercontent.com/mikesprague/skydark-app/master/public/images/skydark-app-icon-64.png
  name: SkyDark
  backUrl: https://skydark.app
  introTitle: "SkyDark Status"
  introMessage: This page shows **real-time** status of the SkyDark PWA and API
